// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szwyrafpdehzulrsetxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6d3lyYWZwZGVoenVscnNldHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzU5MjQsImV4cCI6MjA1Njg1MTkyNH0.bQ5xOXDC6LDB1Xz-UIWVczxAMQPzHU5n8D4A4TUvakI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);